[package]
name = "rm_server"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = {version = "0.4.38", features = ["serde"]}
colored = "2.1.0"
mysql = "25.0.1"
serde = "1.0.205"
toml = "0.8.19"
